services:
  eurofoamdashb:
    # Use your Docker image name here
    image: goswamirohit/eurofoamdashb:v1
    container_name: eurofoamdashb
    restart: unless-stopped
    ports:
      - "3000:3000"
    # This is the key line that tells Docker to read the variables from the .env file
    env_file:
      - .env
      - .env.production

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NODE_OPTIONS=--max-old-space-size=1536
      - JWT_SECRET=${JWT_SECRET}