services:
  slmcmsdashboard:
    # Use your Docker image name here
    image: goswamirohit/slmcmsdashboard:v46
    container_name: slmcmsdashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    # This is the key line that tells Docker to read the variables from the .env file
    env_file:
      - .env
      - .env.production

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_WORKOS_REDIRECT_URI=${NEXT_PUBLIC_WORKOS_REDIRECT_URI}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_MCP_SERVER_URL=${NEXT_PUBLIC_MCP_SERVER_URL}
      - RESEND_MAIL_API=${RESEND_MAIL_API}
      - OPENCAGE_GEO_API=${OPENCAGE_GEO_API}
      - VITE_RADAR_PUBLISHABLE_KEY=${OPENCAGE_GEO_API}
      - RADAR_SECRET_KEY=${RADAR_SECRET_KEY}
      - LOCATIONIQ_KEY=${LOCATIONIQ_KEY}
      - NODE_OPTIONS=--max-old-space-size=1536
      - JWT_SECRET=${JWT_SECRET}